### ISSUE TITLE
programmatically adding markers

### ISSUE THREAD

**Issue by rourke750** [Gjum/CivMap#31]
Hey I am currently trying to create a snitch notification website and I was hoping to use this project to relay player alerts as popping up on the map.  I'm not very good with javascript and have been coding my website using django and I was wondering if you had any recommendations on how to create markers on your map but without having the user click to make them.

Thanks!

**Comment by Gjum** [comment]
I'll have that built-in and more easily accessible in the future, but for now you can copy the [index.html](https://github.com/Gjum/CivMap/blob/master/app/index.html) and other assets from `app/`, and at the end of `index.html` put a script block with something like this, just adapt it to make it read from a webhook:
```html
<script>
CivMap.api.dispatch({type:'UPDATE_FEATURE',feature:{
    "x":-8610,"z":-3046,"id":"SOME_UNIQUE_ID",
    icon:'https://minotar.net/avatar/ttk2/32.png', icon_size: 32,
}})
</script>
```
I just pushed some preliminary API info to the readme, in particular [some info how features are structured](https://github.com/Gjum/CivMap/blob/master/README.md#feature-format), note that the internal API related to collections storage will have to change one more time in the next couple days to make importing/exporting work.

**Comment by rourke750** [comment]
Perfect, if I have your website linked in an ipanel do I still do it that way?

**Comment by Gjum** [comment]
Yes that might work just as well, worth a try.

**Comment by rourke750** [comment]
So I added the civmap stuff like this at the bottom of my page:
> <script>
>function test() {
>CivMap.api.dispatch({type:'UPDATE_FEATURE',feature:{
 >   "x":0,"z":1000,"id":"fdsnjksdfnjklsdfnhjksdfnjksdf",
 >   icon:'https://minotar.net/avatar/ttk2/32.png', icon_size: 32,
> }})
>}
></script>

and using chrome console tried calling test and got CivMap is not defined.

**Comment by Gjum** [comment]
Did you change all the relative urls to absolute urls? For example `<script src="js/bundle.js"></script>` to `<script src="https://civclassics.firebaseapp.com/js/bundle.js"></script>` etc.

**Comment by Gjum** [comment]
Apparently iframes don't work: https://stackoverflow.com/questions/11200924/access-global-variable-in-iframe#11201265

**Comment by rourke750** [comment]
Herm it says iframes would work if you pass a variable in from parent to iframe, would that be easy for you to do or did I not understand what it meant?

**Comment by rourke750** [comment]
So I am able to reference CivMap but it is undefined

**Comment by rourke750** [comment]
Oh herm it might be my side, let me test a little more

**Comment by rourke750** [comment]
Ah perfect that worked.

**Comment by rourke750** [comment]
So I've been playing with https://github.com/Gjum/CivMap/blob/master/app/js/store.js#L200 and it doesnt seem to want to work.

I'm using 
```
<script>
        var features = CivMap.api.getState().features.featuresUser
        for (var key in features) {
         CivMap.api.dispatch({ type: 'REMOVE_FEATURE', feature: features[key] })
        }
</script>
```

**Comment by Gjum** [comment]
`removeFeature` takes just the feature id: https://github.com/Gjum/CivMap/blob/master/app/js/store.js#L223

so you want something like `CivMap.api.dispatch({ type: 'REMOVE_FEATURE', id: key })`
